Organisateur:
    type: entity
    table: organisateur
    id:
        idOrg:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: id_org
            generator:
                strategy: IDENTITY
    fields:
        nom:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
        prenom:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
        email:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
        tel:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
    lifecycleCallbacks: {  }
