Reclamation:
    type: entity
    table: reclamation
    indexes:
        fk_rec_cl:
            columns:
                - id_user
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        contenu:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        etat:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        type:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        date:
            type: date
            nullable: false
        idEvent:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: id_event
        reponse:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
    manyToOne:
        idUser:
            targetEntity: FosUser
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_user:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
