User:
    type: entity
    table: user
    id:
        idUser:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: id_user
            generator:
                strategy: IDENTITY
    fields:
        login:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        mdp:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        role:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
    lifecycleCallbacks: {  }
