events_index:
    path:     /
    defaults: { _controller: "MainBundle:Events:index" }
    methods:  GET

events_show:
    path:     /{idEv}/show
    defaults: { _controller: "MainBundle:Events:show" }
    methods:  GET

events_new:
    path:     /new
    defaults: { _controller: "MainBundle:Events:new" }
    methods:  [GET, POST]

events_edit:
    path:     /{idEv}/edit
    defaults: { _controller: "MainBundle:Events:edit" }
    methods:  [GET, POST]

events_delete:
    path:     /{idEv}/delete
    defaults: { _controller: "MainBundle:Events:delete" }
    methods:  DELETE

events_search:
    path:     /search
    defaults: { _controller: "MainBundle:Events:search"}
accueil:
    path:     /accueil
    defaults: { _controller: "MainBundle:Events:accueil" }
inscription_page:
    path:     /inscription
    defaults: { _controller: "MainBundle:Events:inscription" }
home_page:
    path:     /home_page
    defaults: { _controller: "MainBundle:Events:home" }
